### ISSUE TITLE
Should today's usage be replaced?

### ISSUE THREAD

**Issue by danielenestrom** [svenove/iOSTibberWidget#4]
For me, the usage data for the current day is lagging behind so many hours that it is useless. It is rarely above 1–2 kWh for any given day. That is the kind of lag I have of the usage data in Tibber. Should we replace the daily usage with some other data or is this only happening to me?

**Comment by danielenestrom** [comment]
@svenove do you consistently see today's usage? Mine is at 0–1 kWh during the entire day thanks to the lag of the data coming in from Tibber.

**Comment by svenove** [comment]
@danielenestrom for me, the usage in both widget and app seems accurate and up to date. I suggest contacting support to see if it could be an issue with your account.
